env:
  browser: false
  node: true
  es6: true
extends:
  - "eslint:recommended"
  - "plugin:@typescript-eslint/recommended"
  - "plugin:prettier/recommended"
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - "@typescript-eslint"
ignorePatterns:
  - "packages/api_bo/**/*"
  - "packages/api_m/**/*"
  - "packages/front_bo/src/generated/*"
  - "packages/front_m/src/generated/*"
rules:
  "no-console": error
  # "@typescript-eslint/explicit-function-return-type": warn
  "@typescript-eslint/no-explicit-any": error
  "@typescript-eslint/no-unused-vars": error
  "@typescript-eslint/no-non-null-assertion": error
