name: Branch

on:
  workflow_dispatch:
  push:
    branches:
      - develop
      - main

env:
  REGISTRY_HOSTNAME: docker-registry:5000
  BRANCH: ${{ github.ref_name }}

jobs:
  build-api-bo:
    name: Build API bo
    runs-on: edu-cluster
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Build api image
        run: |
          docker build -f ./packages/api_bo/Dockerfile -t $REGISTRY_HOSTNAME/academy/api-bo-$BRANCH:latest .

      - name: Push api image
        run: |
          docker push $REGISTRY_HOSTNAME/academy/api-bo-$BRANCH:latest

      - name: Rollout api deployment
        run: |
          kubectl -n academy rollout restart deployment/api-bo-$BRANCH

  build-front-bo:
    name: Build Front bo
    runs-on: edu-cluster
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Get .env for frontend from configmap
        run: |
          kubectl -n academy get configmap front-bo-$BRANCH-env -o jsonpath="{.data.env}" > ./packages/front_bo/.env

      - name: Build front image
        run: |
          docker build -f ./packages/front_bo/Dockerfile -t $REGISTRY_HOSTNAME/academy/front-bo-$BRANCH:latest .

      - name: Push front image
        run: |
          docker push $REGISTRY_HOSTNAME/academy/front-bo-$BRANCH:latest

      - name: Rollout api deployment
        run: |
          kubectl -n academy rollout restart deployment/front-bo-$BRANCH          